### ISSUE TITLE
Ability to supply known subdomain names

### ISSUE THREAD

**Issue by michael1026** [gfek/Lepus#12]
I'm assuming the more domains that Lepus knows about, the better it'll work (though, I may be wrong). I have subdomains I've found with other tools that I'd like to supply to Lepus. I know I could manually add them to the files Lepus generates, but I wouldn't want to put domains in the wrong files (i.e. putting a wildcard domain in a non-wildcard file).

**Comment by GKNSB** [comment]
We're working on a new version that has many operational changes in the way the tool works. I don't believe that is a feature that would be useful enough though since it is very easy to just create a wordlist of your already known subdomains and use it as a wordlist with Lepus. Thanks for keeping in touch.

**Comment by gfek** [comment]
marked it as a close issue.
