### ISSUE TITLE
a request

### ISSUE THREAD

**Issue by huitc** [gfek/Lepus#4]
It would be better if you could set up multiple accounts.😁

```
[*]-Searching Censys...
  \__ Rate limit exceeded. See https://www.censys.io/account for rate limit details.
```

**Comment by huitc** [comment]
one more thing.. you can support fofa.so this website? it's useful for me, and I think it will be of great help to other users as well. (google translated

**Comment by GKNSB** [comment]
Hey huitc,

Regarding your feature request for multiple accounts, this is not something we can implement, since that would be in violation of the "terms of use" for many of ther services. 

For instance, Censys clearly states the following: "_Service Access. Registering Customers will identify a username and password ("Account Credentials") that will be used to set up Customer's account ("Account"). Censys Free and Censys Basic customers are permitted only one individual registered user per Account. Non-Paying Customers are permitted only one Account. For the avoidance of doubt, the registration of more than one Censys Free Account or Censys Research Account by a Customer is strictly prohibited. The sharing by any Customer of Account Credentials for any type of Account to access the Service is strictly prohibited. Customer agrees to take all necessary steps to protect the confidentiality of Account Credentials and to ensure that appropriate procedures are in place to prevent misuse._"

Furthermore, regarding the request to add fofa.so as a collector, the service doesn't actually seem that usable or that it yields a good amount of results. Furthermore their API, with the pay per request schema doesn't seem like a viable option. We will look into it more, but I don't think it we'll be implemented any time soon.

Cheers

**Comment by huitc** [comment]
fofa.so must use API?

**Comment by huitc** [comment]
https://github.com/DropsDevopsOrg/ECommerceCrawlers/tree/master/OthertCrawler/0x08fofa

**Comment by GKNSB** [comment]
fofa.so does not look like it's worth implementing. Issue can be closed.

**Comment by huitc** [comment]
ok... ^^''

**Comment by huitc** [comment]
search: `domain="{domainname}"`
like this: https://fofa.so/result?q=domain%3D%22github.com%22&qbase64=ZG9tYWluPSJnaXRodWIuY29tIg%3D%3D&full=true

if `full=true` then show all record else only show records for one year (google translated

**Comment by huitc** [comment]
Non-registered member can view first page only, Non-paid member can view 5 pages 
but you can use `domain=.... && domain!="{Extracted domain 1}" && domain!="{Extracted domain 2}" `

**Comment by huitc** [comment]
can you reopen this 😅
